[build]
  publish = "public"
  command = "npm run build"
  ignore = "git log -1 --pretty=%B | grep dependabot"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


