backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Created {{collection}} “{{slug}}”"
    update: "Updated {{collection}} “{{slug}}”"
    delete: "Deleted {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}--{{minute}}{{second}}{{hour}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "portfolio-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "prettydate", widget: "string" }
      - { label: "small description", name: "description2", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: image }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

 

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Tagline, name: tagline, widget: text }
          - { label: About Blurb, name: aboutblurb, widget: text }
          - {
              label: socials,
              name: social links,
              widget: list,
              fields:
                [
                  { label: Social name, name: prettyLink, widget: text },
                  { label: url, name: url, widget: text },
                ],
            }
          - {label: year, name: year, widget: date}


      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "profile", widget: image }

     


      
