backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Created {{collection}} “{{slug}}”"
    update: "Updated {{collection}} “{{slug}}”"
    delete: "Deleted {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"



local_backend: true
media_folder: static/img
public_folder: /img
media_library:
  name: uploadcare
  config:
    publicKey: 75cf951ef49f5d8b6bdf
    tabs: "file url gdrive instagram"
    
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}--{{minute}}{{second}}{{hour}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "portfolio-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "prettydate", widget: "string" }
      - { label: 'Text Color', name: fgcolor, widget: 'color', allowInput: true, required: false}
      - { label: 'Background Color', name: bgcolor, widget: 'color', allowInput: true,required: false }

      - { label: "small description", name: "description2", widget: "string" }
      - { label: "role", name: "role", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }

      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: image }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - label: "Body 2"
        name: "bodycontent"
        widget: "list" 
        types: 
          - label: Full Image
            name: bodyfullimage
            widget: object
            summary: "{{fields.image}}"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: alt, name: alt, widget: string}

          - label: Text
            name: bodytext
            widget: object
            summary: "{{fields.text}}"
            fields:
              - {label: Text, name: text, widget: markdown}
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "playground"
    label: "playground"
    folder: "src/pages/playground"
    create: true
    slug: "{{slug}}--{{minute}}{{second}}{{hour}}"
    fields:
    - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "playground-post",
      }
    - { label: "Title", name: "title", widget: "string" }

    - { label: "Date", name: "prettydate", widget: "string" }
    - { label: "small description", name: "description2", widget: "string" }
    - { label: "role", name: "role", widget: "string" }
    - { label: "Publish Date", name: "date", widget: "datetime" }

    - { label: "Description", name: "description", widget: "text" }
    - { label: "Thumbnail", name: "thumbnail", widget: image }
    - label: "Body 2"
      name: "bodycontent"
      widget: "list" 
      types: 
        - label: Full Image
          name: bodyfullimage
          widget: object
          summary: "{{fields.image}}"
          fields:
            - {label: Image, name: image, widget: image}
            - {label: alt, name: alt, widget: string}

        - label: Text
          name: bodytext
          widget: object
          summary: "{{fields.text}}"
          fields:
            - {label: Text, name: text, widget: markdown,required: false}
    - { label: "Tags", name: "tags", widget: "list" }

 

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Tagline, name: tagline, widget: text }
          - { label: About Blurb, name: aboutblurb, widget: text }
          - { label: About Description, name: aboutdesc, widget: text }
          - {
              label: current interests,
              name: interests,
              widget: list,
              fields:
                [
                  { label: title, name: title, widget: string },
                  { label: url Label, name: prettyLink, widget: string },
                  { label: url, name: url, widget: string },
                ],
            }

  
          - {
              label: socials,
              name: social links,
              widget: list,
              fields:
                [
                  { label: Social name, name: prettyLink, widget: string },
                  { label: url, name: url, widget: string },
                ],
            }
          - {label: year, name: year, widget: string}
          


      - file: "src/pages/about/index.md"
        label: "play"
        name: "play"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "play-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Featured Image", name: "profile", widget: image }

     


      
